<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOUFpLlK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOUFpLlK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOUFpLlK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOUFpLlK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOUFpLlK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OUFpLlK',
    'container.build_id' => '08f2ff02',
    'container.build_time' => 1600146935,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOUFpLlK');
