#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_Task_new:
  path: /task/
  controller: App\Controller\TaskController::new
app_product_admin_list:
  path: /product/admin/list
  controller : APP\Controller\ProductController::list_admin
app_product_list:
  path: /product/list
  controller : APP\Controller\ProductController::list
app_product_admin_delete:
  path: /product/admin/delete
  controller : APP\Controller\ProductController::delete